version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    
    open-pull-requests-limit: 5

    commit-message:
      prefix: "chore(deps)"
      include: "scope"

    ignore:
      - dependency-name: "@nestjs/cli"
        update-types: ["version-update:semver-major"]

    groups:
      safe-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

      nestjs:
        patterns:
          - "@nestjs/*"

      prisma:
        patterns:
          - "prisma"
          - "@prisma/*"

      linters:
        patterns:
          - "eslint*"
          - "prettier*"
          - "@typescript-eslint/*"
          - "husky"
          - "lint-staged"
          - "@commitlint/*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "chore(deps)"
