# Build stage
FROM node:25-alpine AS builder

WORKDIR /app

# Install pnpm
RUN npm install -g pnpm

# Copy package files
COPY package.json pnpm-lock.yaml ./

# Copy prisma schema for building
COPY prisma/ ./prisma/

# Skip pnpm check & ignore scripts (to skip husky)
ENV SKIP_PNPM_CHECK=true
RUN pnpm install --frozen-lockfile --ignore-scripts

# Copy source code
COPY . .

# Generate Prisma Client & Build
RUN pnpm exec prisma generate
RUN pnpm build

# Production stage
FROM node:25-alpine AS production

WORKDIR /app

# Install pnpm
RUN npm install -g pnpm

# Copy package files
COPY package.json pnpm-lock.yaml ./
COPY prisma/ ./prisma/

# Install only production dependencies
ENV SKIP_PNPM_CHECK=true
RUN pnpm install --frozen-lockfile --prod --ignore-scripts

# Generate Prisma Client for production
RUN pnpm exec prisma generate

# Copy built application from builder stage
COPY --from=builder /app/dist ./dist

# Expose port
EXPOSE 8080

# Accept Build Arguments (Passed via GitHub Actions)
ARG NODE_ENV=development
ARG APP_PORT=8080
ARG DB_HOST
ARG DB_PORT
ARG DB_USERNAME
ARG DB_PASSWORD
ARG DB_DATABASE
ARG REDIS_HOST
ARG REDIS_PORT
ARG REDIS_PASSWORD
ARG REDIS_DB
ARG MINIO_ENDPOINT
ARG MINIO_PORT
ARG MINIO_CONSOLE_PORT
ARG MINIO_ACCESS_KEY
ARG MINIO_SECRET_KEY
ARG MINIO_BUCKET_NAME
ARG MINIO_USE_SSL
ARG CLOUDINARY_CLOUD_NAME
ARG CLOUDINARY_API_KEY
ARG CLOUDINARY_API_SECRET
ARG PINATA_JWT_KEY
ARG PINATA_GATEWAY
ARG DATABASE_URL
ARG JWT_SECRET
ARG JWT_EXPIRES_IN
ARG JWT_REFRESH_SECRET
ARG JWT_REFRESH_EXPIRES_IN
ARG FIREBASE_SERVICE_ACCOUNT_BASE64
ARG SENDGRID_API_KEY
ARG SENDGRID_FROM_EMAIL
ARG SENDGRID_FROM_NAME
ARG OTP_EXPIRY_SECONDS
ARG OTP_MAX_ATTEMPTS
ARG RESET_TOKEN_EXPIRY_SECONDS
ARG LOCATION_IQ_API_KEY
ARG VISION_API_URL
ARG VISION_PORT
ARG MINIO_PUBLIC_URL
ARG QR_HMAC_SECRET
ARG ALGOLIA_APP_ID
ARG ALGOLIA_SEARCH_KEY
ARG ALGOLIA_ADMIN_KEY
ARG POLYGON_RPC_URL
ARG CONTRACT_ADDRESS

# Map ARGs to Runtime Environment Variables
ENV NODE_ENV=$NODE_ENV \
    APP_PORT=$APP_PORT \
    DB_HOST=$DB_HOST \
    DB_PORT=$DB_PORT \
    DB_USERNAME=$DB_USERNAME \
    DB_PASSWORD=$DB_PASSWORD \
    DB_DATABASE=$DB_DATABASE \
    REDIS_HOST=$REDIS_HOST \
    REDIS_PORT=$REDIS_PORT \
    REDIS_PASSWORD=$REDIS_PASSWORD \
    REDIS_DB=$REDIS_DB \
    MINIO_ENDPOINT=$MINIO_ENDPOINT \
    MINIO_PORT=$MINIO_PORT \
    MINIO_CONSOLE_PORT=$MINIO_CONSOLE_PORT \
    MINIO_ACCESS_KEY=$MINIO_ACCESS_KEY \
    MINIO_SECRET_KEY=$MINIO_SECRET_KEY \
    MINIO_BUCKET_NAME=$MINIO_BUCKET_NAME \
    MINIO_USE_SSL=$MINIO_USE_SSL \
    CLOUDINARY_CLOUD_NAME=$CLOUDINARY_CLOUD_NAME \
    CLOUDINARY_API_KEY=$CLOUDINARY_API_KEY \
    CLOUDINARY_API_SECRET=$CLOUDINARY_API_SECRET \
    PINATA_JWT_KEY=$PINATA_JWT_KEY \
    PINATA_GATEWAY=$PINATA_GATEWAY \
    DATABASE_URL=$DATABASE_URL \
    JWT_SECRET=$JWT_SECRET \
    JWT_EXPIRES_IN=$JWT_EXPIRES_IN \
    JWT_REFRESH_SECRET=$JWT_REFRESH_SECRET \
    JWT_REFRESH_EXPIRES_IN=$JWT_REFRESH_EXPIRES_IN \
    FIREBASE_SERVICE_ACCOUNT_BASE64=$FIREBASE_SERVICE_ACCOUNT_BASE64 \
    SENDGRID_API_KEY=$SENDGRID_API_KEY \
    SENDGRID_FROM_EMAIL=$SENDGRID_FROM_EMAIL \
    SENDGRID_FROM_NAME=$SENDGRID_FROM_NAME \
    OTP_EXPIRY_SECONDS=$OTP_EXPIRY_SECONDS \
    OTP_MAX_ATTEMPTS=$OTP_MAX_ATTEMPTS \
    RESET_TOKEN_EXPIRY_SECONDS=$RESET_TOKEN_EXPIRY_SECONDS \
    LOCATION_IQ_API_KEY=$LOCATION_IQ_API_KEY \
    VISION_API_URL=$VISION_API_URL \
    VISION_PORT=$VISION_PORT \
    MINIO_PUBLIC_URL=$MINIO_PUBLIC_URL \
    QR_HMAC_SECRET=$QR_HMAC_SECRET \
    ALGOLIA_APP_ID=$ALGOLIA_APP_ID \
    ALGOLIA_SEARCH_KEY=$ALGOLIA_SEARCH_KEY \
    ALGOLIA_ADMIN_KEY=$ALGOLIA_ADMIN_KEY \
    POLYGON_RPC_URL=$POLYGON_RPC_URL \
    CONTRACT_ADDRESS=$CONTRACT_ADDRESS

# Start the application
CMD ["node", "dist/src/main.js"]
